baseURL = "/"
title = "LocalStack Docs"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"
persistence = "persistence"

[params.taxonomy]
taxonomyCloud = [] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = [] # if used, must have same length as taxonomyCloud
taxonomyPageHeader = ["tags", "categories", "persistence"] # set taxonomyPageHeader = [] to hide taxonomies on the page headers

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-101988473-1"

# Language configuration

[languages]
[languages.en]
title = "Docs"
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.en.params]
description = "LocalStack Documentation"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "RSS"]

[params]
copyright = "LocalStack"
privacy_policy = "https://localstack.cloud/privacy-policy/"

# this link will be followed when clicking on the brand icon
brand_link = "https://localstack.cloud"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://localstack.cloud/docs/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/localstack/docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/localstack/localstack"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488cc3"

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

disable_click2copy_chroma = true

# Enable Algolia DocSearch
[params.search.algolia]
appId = "XBW1JU7CW5"
apiKey = "6b0341e2f50196d328d088dbb5cd6166"
indexName = "localstack"

# User interface configuration
[params.ui]
# Set the title of the Table of Contents on the right side of the article page
toc_title = "Table of Contents"
# Set to true to enable the menu folding in the sidebar
sidebar_menu_foldable = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
# Limit for number of children pages (This is an undocumented option)
sidebar_menu_truncate = 128

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Thanks for participating in keeping our docs well maintained. Learn more about how you can <a target="_blank" href="https://localstack.cloud/community/get-involved/">get involved.</a>'
no = 'Sorry to hear that. Please <a target="_blank" href="https://github.com/localstack/docs/issues/new">tell us how we can improve.</a>'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/localstack"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Discussion"
	url = "https://discuss.localstack.cloud/"
	icon = "fa fa-comments"
	desc = "Community discussions on GitHub"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/localstack"
	icon = "fab fa-stack-overflow"
	desc = "Practical questions and curated answers"

# Developer relevant links
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/localstack/"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[params.links.developer]]
	name = "Issue tracker"
	url = "https://github.com/localstack/localstack/issues"
	icon = "fa fa-bug"
	desc = "LocalStack issue tracker"
[[params.links.developer]]
	name = "Slack"
	url = "https://localstack.cloud/slack"
	icon = "fab fa-slack"
	desc = "Chat with other project developers"


[params.localstack]
# LocalStack specific configuration values
latest_version = "3.4.0"

[params.localstack.cli_links]
# Configure the different download links for the cli-binary-download shortcode
[[params.localstack.cli_links.macos]]
	name = "Intel (AMD64)"
	url = "https://github.com/localstack/localstack-cli/releases/download/v<latest-version>/localstack-cli-<latest-version>-darwin-amd64-onefile.tar.gz"
	icon = "fab fa-apple"
[[params.localstack.cli_links.linux]]
	name = "x86-64"
	url = "https://github.com/localstack/localstack-cli/releases/download/v<latest-version>/localstack-cli-<latest-version>-linux-amd64-onefile.tar.gz"
	icon = "fab fa-linux"
[[params.localstack.cli_links.linux]]
	name = "ARM64"
	url = "https://github.com/localstack/localstack-cli/releases/download/v<latest-version>/localstack-cli-<latest-version>-linux-arm64-onefile.tar.gz"
	icon = "fab fa-linux"
[[params.localstack.cli_links.windows]]
	name = "64-bit"
	url = "https://github.com/localstack/localstack-cli/releases/download/v<latest-version>/localstack-cli-<latest-version>-windows-amd64-onefile.zip"
	icon = "fab fa-windows"

# hugo module configuration

[module]
  [module.hugoVersion]
    extended = true
    min = "0.125.4"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false    
