blank_issues_enabled: true
contact_links:
  - name: ðŸ“– LocalStack Documentation
    url: https://docs.localstack.cloud/overview/ 
    about: Use our docs to answer your questions!
  - name: ðŸ’¬ LocalStack Community Support (Slack)
    url: https://localstack.cloud/slack 
    about: Please ask and answer questions in our Slack.