name: Update Parity Docs
on:
  schedule:
    - cron: 0 5 * * MON
  workflow_dispatch:

jobs:
  update-parity-coverage-docs:
    name: Update Parity Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: docs

      - name: Checkout localstack (community)
        uses: actions/checkout@v2
        with:
          repository: localstack/localstack
          fetch-depth: 0
          path: localstack

      - name: Set up system wide dependencies
        run: |
          sudo apt-get install libsasl2-dev jq wget

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Download metrics data from Pro test pipeline (GitHub)
        working-directory: localstack
        run: |
          mkdir -p target/metrics-raw
          cd target/metrics-raw
          gh run download --repo localstack/localstack-ext -n parity-metric-ext-raw
          cd ../../
          tree target
          # TODO Get the latest successful build on master
          # TODO the runs on master often do NOT run the parity tests!
          #   RUN_ID=$(gh run list --limit 1 --branch master --repo localstack/localstack-ext --workflow "Integration Tests" --json databaseId,conclusion --jq '.[] | select(.conclusion=="success")' | jq -r .databaseId)
          #   gh run download $RUN_ID --repo localstack/localstack-ext -n parity-metric-ext-raw
        env:
          GITHUB_TOKEN: ${{ secrets.PRO_ACCESS_TOKEN }}

      - name: Download metrics data from latest Community test run (CircleCI)
        working-directory: docs
        # TODO remove branch param here (use metrics data from master branch builds)
        run: ./scripts/get_latest_circleci_metrics.sh ../localstack/target feature_metric_coverage_collection

      - name: Cache LocalStack community dependencies (venv)
        uses: actions/cache@v2
        with:
          path: localstack/.venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('localstack/setup.cfg') }}

      - name: Install dependencies
        working-directory: localstack
        run: make install-dev entrypoints

      - name: Create Parity Coverage Docs
        working-directory: localstack
        run: |
          source .venv/bin/activate
          python3 -m scripts.coverage_docs_utility target/metrics-implementation-details target/metrics-raw
          # Move the resulting markdown file to the docs repo
          mv -f target/metrics-raw/coverage.md ../docs/content/en/localstack/

      - name: Check for changes
        id: check-for-changes
        working-directory: docs
        run: |
          # Check if there are changed files and store the result in resources/diff-check.log
          # Check against the PR branch if it exists, otherwise against the main
          # Store the result in resources/diff-check.log and store the diff count in the GitHub Action output "diff-count"
          mkdir -p resources
          (git diff --name-only origin/parity-coverage-auto-updates content/en/localstack/ 2>/dev/null || git diff --name-only origin/main content/en/localstack/ 2>/dev/null) | tee resources/diff-check.log
          echo "::set-output name=diff-count::$(cat resources/diff-check.log | wc -l)"

      - name: Read PR markdown template
        if: ${{ success() && steps.check-for-changes.outputs.diff-count != '0' && steps.check-for-changes.outputs.diff-count != '' }}
        id: template
        uses: juliangruber/read-file-action@v1
        with:
          path: docs/.github/bot_templates/PARITY_COVERAGE_DOCS_PR.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        if: ${{ success() && steps.check-for-changes.outputs.diff-count != '0' && steps.check-for-changes.outputs.diff-count != '' }}
        with:
          path: docs
          title: "Update Parity Coverage Docs"
          body: "${{ steps.template.outputs.content }}"
          branch: "parity-coverage-auto-updates"
          author: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
          committer: "LocalStack Bot <localstack-bot@users.noreply.github.com>"
          commit-message: "update generated parity coverage docs"
          token: ${{ secrets.PRO_ACCESS_TOKEN }}
